name: Deployment
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
env:
  #Workflow level
  #Will be available in all jobs in the workflows ** unless a job overwrites this variable
  MONGODB_DB_NAME: gha-demo-db-name
jobs:
  test:
    # Here we can specify the environment we want for this specific job
    # So when the secrets context obj access the username or password it will only access the secrets from the testing environment & not general secrets repository wide
    environment: testing
    # If we provide the environment here it will only avaivable in the test job
    # For testing we want a different DB with its own credentials, that differs from our prod db 
    env:
      MONGODB_CLUSTER_ADDRESS: cluster0.agb9y3z.mongodb.net
      # We can now access our repository level secret credentials using the github secrets contexts object
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
      #Using env in run instruction you can itroplate 
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
      # The env object gives us access to all the env varibales in this job 
        run: echo "${{secrets.MONGODB_USERNAME}}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
      # Mongodb username should  not be avaiable because it is specific to the that job
      # but the Mongo db Name will be avaiable because it is at workflow level 
        run: |        
          echo "MONGODB_USERNAME: ${{secrets.MONGODB_USERNAME}}"
          echo "MONGODB_DB_NAME: ${{env.MONGODB_DB_NAME}}"